In [1]:
import numpy as np
import tensorflow_datasets as tfdf
from sklearn.datasets import load_digits
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
import joblib
from sklearn.metrics import confusion_matrix
from sklearn import svm


In [2]:
df=load_digits()

In [3]:
X=df.images

In [4]:
X.shape
X_len=len(df.images)

In [5]:
y=df.target

In [44]:
X=df.images.reshape((-1,8*8))


In [45]:
from sklearn.model_selection import train_test_split

In [46]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.2)

In [47]:
X_train[0]

array([ 0.,  0.,  3., 14.,  1.,  0.,  0.,  0.,  0.,  0., 12., 12.,  0.,
        0.,  0.,  0.,  0.,  3., 16.,  6.,  0.,  0.,  0.,  0.,  0.,  5.,
       16.,  2.,  0.,  0.,  0.,  0.,  0.,  6., 16.,  2.,  5.,  2.,  0.,
        0.,  0.,  4., 16.,  2., 12., 15.,  2.,  0.,  0.,  1., 14., 13.,
        2., 13., 11.,  0.,  0.,  0.,  3., 11., 16., 13.,  4.,  0.])

In [48]:
import matplotlib.pyplot as plt

In [50]:
df.images

array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0.,  0.],
        [ 0.,  0.,  3., ..., 14.,  0.,  0.],
        [ 0.,  0.,  8., ..., 16.,  0.,  0.],
        ...,
        [ 0.,  9., 16., ...,  0.,  0.,  0.],
        [ 0.,  3., 13., ..., 11.,  5.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.]],

       ...,

       [[ 0.,  0.,  1., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ...,  2.,  1.,  0.],
        [ 0.,  0., 16., ..., 16.,  5.,  0.

In [51]:
X_train.shape

(1437, 64)

In [52]:
X_train=np.array(X_train/256)

In [53]:
X_test=np.array(X_test/256)

In [54]:
X_train.shape

(1437, 64)

In [55]:
clf=MLPClassifier(solver='adam',activation='relu',hidden_layer_sizes=(64,64))
print(clf)

MLPClassifier(hidden_layer_sizes=(64, 64))


In [56]:
clf.fit(X_train,y_train)

c:\python3.9\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(64, 64))

In [57]:
y_train

array([6, 0, 0, ..., 2, 7, 1])

In [58]:
X_train.ndim

2

In [59]:
prediction=clf.predict(X_test)

In [60]:
accu=clf.score(X_test,y_test)
print('accuracy',accu)

accuracy 0.9305555555555556


In [64]:
filename='hand_recogintion.sav'


In [65]:
# joblib.dump(filename)

TypeError: dump() missing 1 required positional argument: 'filename'

In [66]:
acc=confusion_matrix(y_test,prediction)

In [67]:
acc

array([[32,  0,  0,  0,  1,  0,  0,  0,  0,  0],
       [ 0, 26,  1,  0,  0,  0,  0,  0,  0,  1],
       [ 0,  1, 31,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0, 33,  0,  1,  0,  0,  0,  0],
       [ 0,  1,  0,  0, 45,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  0,  0, 43,  0,  0,  1,  2],
       [ 1,  0,  0,  0,  0,  0, 34,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 33,  0,  1],
       [ 0,  3,  1,  0,  0,  1,  0,  0, 24,  1],
       [ 0,  0,  0,  2,  1,  1,  0,  1,  1, 34]], dtype=int64)

In [68]:
def accuracy(confusion_matrix):
    diaognal_sum=confusion_matrix.trace()
    sum_of_all_element=confusion_matrix.sum()
    return diaognal_sum/sum_of_all_element

In [69]:
accuracy(acc)

0.9305555555555556