In [2]:
from sklearn.preprocessing import LabelEncoder

In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import neighbors,metrics,svm

In [8]:
df=pd.read_csv('car.data',sep=',',header=None)

In [7]:
df

vhigh vhigh.1      2   2.1  small   low  unacc
0     vhigh   vhigh      2     2  small   med  unacc
1     vhigh   vhigh      2     2  small  high  unacc
2     vhigh   vhigh      2     2    med   low  unacc
3     vhigh   vhigh      2     2    med   med  unacc
4     vhigh   vhigh      2     2    med  high  unacc
...     ...     ...    ...   ...    ...   ...    ...
1722    low     low  5more  more    med   med   good
1723    low     low  5more  more    med  high  vgood
1724    low     low  5more  more    big   low  unacc
1725    low     low  5more  more    big   med   good
1726    low     low  5more  more    big  high  vgood

[1727 rows x 7 columns]

In [9]:
df.columns=['buying','maint','doors','persons','lug_boot','safety','class']

In [10]:
df

buying  maint  doors persons lug_boot safety  class
0     vhigh  vhigh      2       2    small    low  unacc
1     vhigh  vhigh      2       2    small    med  unacc
2     vhigh  vhigh      2       2    small   high  unacc
3     vhigh  vhigh      2       2      med    low  unacc
4     vhigh  vhigh      2       2      med    med  unacc
...     ...    ...    ...     ...      ...    ...    ...
1723    low    low  5more    more      med    med   good
1724    low    low  5more    more      med   high  vgood
1725    low    low  5more    more      big    low  unacc
1726    low    low  5more    more      big    med   good
1727    low    low  5more    more      big   high  vgood

[1728 rows x 7 columns]

In [14]:
df.notnull().count()

buying      1728
maint       1728
doors       1728
persons     1728
lug_boot    1728
safety      1728
class       1728
dtype: int64

In [20]:
df.dtypes.value_counts()

object    7
dtype: int64

In [21]:
X=df[['buying','maint','doors','persons','lug_boot','safety']]
y=df['class']

In [22]:
X

buying  maint  doors persons lug_boot safety
0     vhigh  vhigh      2       2    small    low
1     vhigh  vhigh      2       2    small    med
2     vhigh  vhigh      2       2    small   high
3     vhigh  vhigh      2       2      med    low
4     vhigh  vhigh      2       2      med    med
...     ...    ...    ...     ...      ...    ...
1723    low    low  5more    more      med    med
1724    low    low  5more    more      med   high
1725    low    low  5more    more      big    low
1726    low    low  5more    more      big    med
1727    low    low  5more    more      big   high

[1728 rows x 6 columns]

In [23]:
X=np.array(X)

In [27]:
X

array([['vhigh', 'vhigh', '2', '2', 'small', 'low'],
       ['vhigh', 'vhigh', '2', '2', 'small', 'med'],
       ['vhigh', 'vhigh', '2', '2', 'small', 'high'],
       ...,
       ['low', 'low', '5more', 'more', 'big', 'low'],
       ['low', 'low', '5more', 'more', 'big', 'med'],
       ['low', 'low', '5more', 'more', 'big', 'high']], dtype=object)

In [28]:
Le=LabelEncoder()

In [30]:
for i  in range(len(X[0])):
    X[:,i]=Le.fit_transform(X[:,i])
print(X)

[[3 3 0 0 2 1]
 [3 3 0 0 2 2]
 [3 3 0 0 2 0]
 ...
 [1 1 3 2 0 1]
 [1 1 3 2 0 2]
 [1 1 3 2 0 0]]


In [31]:
label_mapping={
    
'unacc':0, 'acc':1, 'good':2, 'vgood':3
    
}

In [34]:
y=y.map(label_mapping)

In [37]:
X.shape

(1728, 6)

In [38]:
y.shape

(1728,)

In [39]:
knn=svm.SVC()


In [40]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [41]:
knn.fit(X_train,y_train)

SVC()

In [42]:
prediction=knn.predict(X_test)

In [45]:
accuracy=metrics.accuracy_score(y_test,prediction)
print("prediction:",prediction)
print('accurancy:',accuracy)


prediction: [0 0 0 0 0 1 0 0 0 0 3 0 0 1 0 0 0 1 0 1 3 0 1 0 0 0 1 0 0 0 0 1 0 0 1 0 0
 0 0 1 0 0 0 2 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 1 2 0 0 0 0 0
 0 1 1 0 1 0 0 1 0 0 0 1 0 0 2 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 3 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 3 0 0 3
 0 0 0 0 1 0 0 0 0 1 0 1 2 0 2 1 1 0 0 0 3 0 0 0 0 0 0 0 0 1 0 1 1 2 1 0 1
 1 3 0 0 0 1 0 1 0 0 0 0 0 0 1 0 3 0 0 0 1 0 1 1 0 1 0 0 1 0 0 0 0 0 0 0 2
 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1 1 0 1 1
 1 0 0 3 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 3 0 1 0 1 0 0 0 1 0 1 0 0 3 0 0
 0 0 0 0 0 0 1 0 0 0 0 1 3]
accurancy: 0.9190751445086706


In [47]:
a=324
print('actual value:',y[a])
print('predcted value:',knn.predict(Xa]))

actual value: 0


ValueError: Expected 2D array, got 1D array instead:
array=[3. 1. 0. 0. 2. 1.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.